services:
  # Backend Service
  - type: web
    name: collab-board-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_URL
        value: https://collab-board-frontend.onrender.com

  # Frontend Service
  - type: static
    name: collab-board-frontend
    buildCommand: npm install && npm run build
    staticPublicPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://collab-board-backend.onrender.com
